# Quickstart: Black Duck Security Scan Action with polaris:
#     https://documentation.blackduck.com/bundle/bridge/page/documentation/t_github-polaris-quickstart.html
name: Polaris Security Scan
on:
  push:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  pull_request:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  workflow_dispatch: {}
jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Polaris Security Scan
        id: polaris-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          ### SCANNING: Required fields
          polaris_server_url: ${{ vars.POLARIS_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          ### ASSESSMENT TYPES
          polaris_application_name: CarOffers
          polaris_project_name: CarOffer
          polaris_onboarding: true
          polaris_branch_name: githubactions
          polaris_assessment_types: SCA  # Comma-separated list: SAST,SCA,DAST
          polaris_test_sca_type: SCA-PACKAGE,SCA-SIGNATURE
